@baseUrl = http://localhost:3000

###
GET {{baseUrl}}/

###
GET {{baseUrl}}/api/users

###
POST {{baseUrl}}/api/users/ekle
Content-type: application/json

{
 "isim":"Alvin",
 "userName":"Alvin2134",
 "sifre":"123456"
}

###
DELETE {{baseUrl}}/api/users/697b9baea28125dcf7ba80e5
Content-type: application/json
###
PATCH {{baseUrl}}/api/users/697cc19c9e836f7c71e299b3
Content-type: application/json

{
 "isim": "Mehmet",
 "userName": "mehmet5156"
}

